# Generated by Django 4.0.4 on 2022-06-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
