# Generated by Django 4.0.3 on 2022-03-09 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='cards.question'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('answer', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='cards.answer')),
                ('deck', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='decks.deck')),
                ('question', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='cards.question')),
            ],
        ),
    ]
