# Generated by Django 4.0.4 on 2022-06-07 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_added_auto_populating_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.question'),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.answer'),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.question'),
        ),
    ]
