# Generated by Django 4.0.5 on 2022-06-13 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_make_fields_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.answer'),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.question'),
        ),
    ]
