# Generated by Django 4.0.5 on 2022-06-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_make_card_relations_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='question_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
